#
#
#
#
#

#mlxtranFileName <- "C:/Users/hnyberg/Dropbox/Doktorandsaker/WarfarinSAEM/Monolix/WarfSAEM2comp_run2.mlxtran"
#dataPath <- "C:/Users/hnyberg/Dropbox/Doktorandsaker/WarfarinSAEM/Monolix/SSE30_datasets"
#i=5

doMlxtranPrep <- function(mlxtranFileName, dataSetList){
  
  # Read in Mlxtran and separate name from extension
  mlxtranFile <- readLines(mlxtranFileName)
  mlxtranFileNameNoExt <- sub("\\.[[:alnum:]]+$", "", basename(as.character(mlxtranFileName)))
  
  # Parse the inital estimates
  
    # First find the start and end of the parameter block
  initialValuesStartRowNumber <- grep("initialValues", mlxtranFile)
  endRows <- grep("}", mlxtranFile)
  initialValuesEndRowNumber <- endRows[which(endRows > initialValuesStartRowNumber)[1]]
  
    # Take those rows from the model code list
  initialValuesRowsList <- mlxtranFile[(initialValuesStartRowNumber+1):(initialValuesEndRowNumber-1)]
  
    # Parse in all parameter definition rows as a list of lists
  paramNamesAndValues <- sapply(initialValuesRowsList, function(x){
    
    # Remove the pesky whitespace at the start, the equals sign, 
    # any commas, and any specific 
    x <- gsub("=", " ", x)
    x <- gsub("  ", "", x)
    x <- gsub(",", "", x)
    x <- gsub('\\s.meth.{2,}', "", x)
    
    #Split up the string based on single white space between the bits.
    strsplit(x, " ")
    
  })
  
  
#   colOne <- "Model"
#   colNames <- c(colOne)
#   values <- c(mlxtranFileNameNoExt)
#   
#   for(i in 1:length(paramNamesAndValues)){
#     # Populate a vector of parameter names
#     colNames <- c(colnames, paramNamesAndValues[[i]][[1]])
#     
#     # Populate a vector of values
#     values <- c(values, as.numeric(paramNamesAndValues[[i]][[2]]))
#     
#   }
  
  
  
  
  colNames <- c(mlxtranFileNameNoExt, colnames)
  
  
  # Add a descriptive comment on the first row
  mlxtranFile[[1]] <- "; This model was generated by R from a user supplied template. R code author: Henrik B. Nyberg"
  
  # Find and remove any Graphics and Algorithm settings
  settingsRowNumbers <- c(grep("settingsG", mlxtranFile), grep("settingsA", mlxtranFile))
  mlxtranFile <- mlxtranFile[-settingsRowNumbers]
  
  # Find the DATA line and assume the path and file name comes on the consecutive lines... not brilliant
  dataRowNumber <- grep("^DATA", mlxtranFile)
  dataPathRowNumber <- dataRowNumber + 1
  dataFileRowNumber <- dataRowNumber + 2
  
  # Find the DESCRIPTION line and assume the next line should be altered
  descRowNumber <- grep("^DESCRIPTION", mlxtranFile) + 1
  
  # Find the resultFolder line
  resFolderRowNumber <- grep("resultFolder", mlxtranFile)
  
  # Create one mlxtran file for each dataset
  nDataSets <- length(dataSetList)
  for(i in 1:nDataSets){
    newMlxFileName <- paste0("mlxest", i, ".mlxtran")
    newMlxResFolderName <- paste0(mlxtranFileNameNoExt, i)
    newMlxFile <- mlxtranFile
    newMlxFile[[descRowNumber]] <- newMlxFileName
    newMlxFile[[dataPathRowNumber]] <- paste0('    path = "%MLXPROJECT%/Data/', '",')
    newMlxFile[[dataFileRowNumber]] <- paste0('    file ="', mlxDataFileList[[i]], '",')
    newMlxFile[[resFolderRowNumber]] <- paste0('        resultFolder = "%MLXPROJECT%/', newMlxResFolderName, '/"},')
    fileConn<-file(newMlxFileName)
    writeLines(newMlxFile, fileConn)
    close(fileConn)
  }
    
  return()
}
