# mlxtranFileName <- mlxModelList[1]
#
#

doMlxtranPrep <- function(mlxtranFileName, dataSetList){
  
  # Read in Mlxtran and separate name from extension
  mlxtranFile <- readLines(mlxtranFileName)
  mlxtranFileNameNoExt <- sub("\\.[[:alnum:]]+$", "", basename(as.character(mlxtranFileName)))
  
### Parse the inital estimates
  
    # First find the start and end of the parameter block
  initialValuesStartRowNumber <- grep("initialValues", mlxtranFile)
  endRows <- grep("}", mlxtranFile)
  initialValuesEndRowNumber <- endRows[which(endRows > initialValuesStartRowNumber)[1]]
  
    # Take those rows from the model code list
  initialValuesRowsList <- mlxtranFile[(initialValuesStartRowNumber+1):(initialValuesEndRowNumber-1)]
  
    # Parse in all parameter definition rows as a list of lists x <- initialValuesRowsList[[1]]

  x <- initialValuesRowsList

    # Remove the pesky whitespace at the start, the equals sign, 
    # any commas, and any other things 
  x <- gsub("=", " ", x)
  x <- gsub("  ", "", x)
  x <- gsub(",", "", x)
  x <- gsub('\\s.meth.{2,}', "", x)
  x <- gsub("pop", "", x)
  x <- gsub("_", "", x)
  x <- gsub("y1", "", x)
  
    # Split up the string based on single white space between the bits.
  x <- strsplit(x, " ")
  
  # Put them together 
  
  colNames <- c("Model", do.call("rbind", x)[,1])
  
  row <- c(quote(mlxtranFileNameNoExt), do.call("rbind", x)[,2])
  
  # build up the call to data frame with column names and one row of data
  callString <- paste("data.frame(", paste(colNames, row, sep = " = ", collapse = ","), ")")
  
  # evaluate the call to data.frame
  initialEstimates <- eval(parse(text = callString))


### Edit and write out the model file

  # Add a descriptive comment on the first row
  mlxtranFile[[1]] <- "; This model was generated by R from a user supplied template. R code author: Henrik B. Nyberg"
  
  # Find and remove any Graphics and Algorithm settings
  settingsRowNumbers <- c(grep("settingsG", mlxtranFile), grep("settingsA", mlxtranFile))
  mlxtranFile <- mlxtranFile[-settingsRowNumbers]
  
  # Find the DATA line and assume the path and file name comes on the consecutive lines... not brilliant
  dataRowNumber <- grep("^DATA", mlxtranFile)
  dataPathRowNumber <- dataRowNumber + 1
  dataFileRowNumber <- dataRowNumber + 2
  
  # Find the DESCRIPTION line and assume the next line should be altered
  descRowNumber <- grep("^DESCRIPTION", mlxtranFile) + 1
  
  # Find the resultFolder line
  resFolderRowNumber <- grep("resultFolder", mlxtranFile)
  
  # Create one mlxtran file for each dataset
  nDataSets <- length(dataSetList)
  for(i in 1:nDataSets){
    newMlxFileName <- paste0(mlxtranFileNameNoExt, "_", i, ".mlxtran")
    newMlxResFolderName <- paste0(mlxtranFileNameNoExt, i)
    newMlxFile <- mlxtranFile
    newMlxFile[[descRowNumber]] <- names(mlxtranFileName)
    newMlxFile[[dataPathRowNumber]] <- paste0('    path = "%MLXPROJECT%/Data/', '",')
    newMlxFile[[dataFileRowNumber]] <- paste0('    file ="', dataSetList[[i]], '",')
    newMlxFile[[resFolderRowNumber]] <- paste0('        resultFolder = "%MLXPROJECT%/', newMlxResFolderName, '/"},')
    fileConn<-file(newMlxFileName)
    writeLines(newMlxFile, fileConn)
    close(fileConn)
  }
    
  return(initialEstimates)
}
